commands:
- id: tool.add_generic_device
  icon: device.svg
  tooltip: Place a generic device on the canvas
  uuid: f1831bfa-9f66-461c-8a1d-6c5440dc314b
- id: tool.select
  icon: select.svg
  default_key: S
  uuid: 6295355a-fa7e-474e-b0d1-825b9a237280
- id: tool.move
  icon: move.svg
  default_key: G
  tooltip: Grab/Move Selection
  uuid: 7ebb2f9c-eb05-43e4-9531-f58f1e4847e9
- id: tool.wire
  icon: wire.svg
  default_sequence:
  - W
  - A
  uuid: c4c49dee-9a8a-4df3-8bf4-09ed795d13ff
- id: tool.measure
  icon: ruler.svg
  default_sequence:
  - M
  - E
  uuid: 66d2bf4e-5235-4baf-b949-05fc95cca8fa
- id: device.create_wizard
  icon: wizard.svg
  uuid: e7d71871-de52-4863-afc1-1ec01be58af7
- id: edit.rotate_cw
  icon: rotate_cw.svg
  default_key: Space
  uuid: 4a88e033-860e-4b9b-9140-338b49c40e61
- id: edit.rotate_ccw
  icon: rotate_ccw.svg
  default_key: Shift+Space
  uuid: aae036a2-4ebc-4f27-8247-2476996f7871
- id: edit.delete
  icon: trash.svg
  default_key: Delete
  uuid: e5f01b07-dd65-4fbc-9d0f-59b83cdc0a0b
- id: edit.undo
  icon: undo.svg
  default_key: Ctrl+Z
  uuid: eed2f62d-aa9f-4bc2-a54f-72899e52122d
- id: edit.redo
  icon: redo.svg
  default_key: Ctrl+Shift+Z
  uuid: 76d4f934-9a88-4fca-8d8b-81503224c354
- id: view.zoom_extents
  icon: zoom_all.svg
  default_sequence:
  - Z
  - E
  uuid: 6a4d16c9-6733-4141-8cd8-1171c60088e4
- id: view.zoom_selected
  icon: zoom_sel.svg
  default_sequence:
  - Z
  - S
  uuid: b0fe1764-78d7-4199-bfc1-079b243b49a1
- id: view.toggle_grid
  icon: grid.svg
  uuid: c6b94895-d9e5-4c4b-b202-14426f01b9bb
- id: view.toggle_property_panel
  icon: panel.svg
  default_key: Tab
  uuid: 8cb57c15-ca0f-4bf1-9e0a-b8c161985594
- id: view.toggle_project_browser
  icon: browser.svg
  uuid: fa7664bb-217f-4a18-b763-2b0c649957de
- id: view.toggle_library
  icon: library.svg
  uuid: de250c9d-f25a-481d-b8bb-29da11cde04e
- id: view.reset_layout
  icon: reset.svg
  uuid: 4390ebb9-c044-488c-917e-658bdf35e428
- id: file.new
  icon: new.svg
  default_key: Ctrl+N
  uuid: d24f41dd-f88b-4c97-a5ac-1ed6c40497ea
- id: file.open
  icon: open.svg
  default_key: Ctrl+O
  uuid: ca077cf8-9a77-4fed-a091-13009b7382b2
- id: file.save
  icon: save.svg
  default_key: Ctrl+S
  uuid: 25d186c1-e3ab-4ca7-a1ed-8d8fa811976d
- id: file.exit
  default_key: Alt+F4
  uuid: 90522229-e8d5-4860-af69-c8e384a5a01a
- id: file.export_bom
  icon: bom.svg
  tooltip: Generate Bill of Materials
  uuid: aaceb7da-39e0-4647-82e1-3af331cbdf40
- id: file.export_wirelist
  icon: wirelist.svg
  tooltip: Generate Wire Cut List
  uuid: 6430b1a7-e043-46d2-a321-99b7c9b34f3b
