[pytest]
minversion = 6.0
addopts = -ra -q
testpaths = tests
norecursedirs = tests/archive_legacy
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .

markers =
	integration: marks integration tests (deselect with '-m "not integration"')
	gui: marks GUI tests (deselect with '-m "not gui"')
