"""
Test that devices can only be created via the API, with UUIDs generated in infra, and that no device is ever created directly from the UI or with a user-supplied ID.
"""
import pytest
from api.manager import APIManager
from core.device import Device

def test_device_creation_enforced_by_api(monkeypatch):
    api = APIManager.get_instance()
    # Try to create a device directly with a non-UUID id (should raise ValueError)
    user_id = "user-supplied-id"
    with pytest.raises(ValueError):
        Device(id=user_id, label="ShouldNotExist")
    # Now use the API to create a device
    created = api.create_device("ValidDevice")
    # All devices in the harness must have UUIDs generated by infra
    import uuid
    for dev in api.context.harness.devices:
        try:
            uuid_obj = uuid.UUID(dev.id)
        except Exception:
            pytest.fail(f"Device with non-UUID id found: {dev.id}")
    # There should be no device with the user-supplied id
    assert all(dev.id != user_id for dev in api.context.harness.devices), "Device with user-supplied id found in harness!"
    # Clean up for test isolation
    api.context.harness.devices = [d for d in api.context.harness.devices if d.id != created.id]
